apiVersion: v1
kind: Service
metadata:
  name: redis
  labels:
    app: redis
spec:
  type: ClusterIP
  clusterIP: None
  selector:
    app: redis
    # role: master
  ports:
    - protocol: TCP
      port: 6379
      targetPort: redis-port
