version: '3.9'
services:
  app:
    build: .
    volumes:
      - ./.env.docker:/env/.env
    ports:
      - 8080:8080
  
  redis:
    image: redis:6.2.6-alpine
    command: redis-server --requirepass verysecretpassword
    volumes:
      - ccp-redis-data:/data

volumes:
  ccp-redis-data:
