apiVersion: v1
data:
  .env: |
    HOST=0.0.0.0
    PORT=8080
    URL_EX={{ .Values.urlExpiration }}

    REDIS_HOST={{ .Release.Name }}-redis-service
    REDIS_PORT=6379
    REDIS_DB=0
kind: ConfigMap
metadata:
  creationTimestamp: null
  name: {{ .Release.Name }}-shortener-config
