apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Release.Name }}-redis
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 100Mi
  hostPath:
    path: /data/{{ .Release.Name }}-redis/
