apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: {{ .Release.Name }}-redis
  name: {{ .Release.Name }}-redis
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Release.Name }}-redis
  strategy: { }
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: {{ .Release.Name }}-redis
    spec:
      containers:
        - image: redis:6.2.6-alpine
          name: redis
          env:
            - name: REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: REDIS_PASSWORD
                  name: {{ .Release.Name }}-redis-secret
          command: [ "redis-server" ]
          args: [ "--requirepass", $(REDIS_PASSWORD) ]
          ports:
            - containerPort: 6379
          resources: { }
          volumeMounts:
            - mountPath: /data
              name: data
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: {{ .Release.Name }}-redis-pvc
status: { }
