apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-shortener-service
spec:
  selector:
    app: {{ .Release.Name }}-shortener
  ports:
    - protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: 8080
