apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: {{ .Release.Name }}-shortener
  name: {{ .Release.Name }}-shortener
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}-shortener
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: {{ .Release.Name }}-shortener
    spec:
      containers:
      - image: radinshayanfar/ccp:1.1
        name: {{ .Release.Name }}-shortener
        resources: 
          requests:
            cpu: "40m"
        ports:
          - containerPort: 8080
        env:
          - name: REDIS_SECRET
            valueFrom:
              secretKeyRef:
                key: REDIS_PASSWORD
                name: {{ .Release.Name }}-redis-secret
        volumeMounts:
          - mountPath: /env/.env
            subPath: .env
            name: config-map
            readOnly: true
      volumes:
        - name: config-map
          configMap:
            name: {{ .Release.Name }}-shortener-config
status: {}
